module.exports = {
  AddReactions: "Añadir reacciones",
  Administrator: "Administrador",
  AttachFiles: "Adjuntar archivos",
  BanMembers: "Prohibir miembros",
  ChangeNickname: "Cambiar apodo",
  Connect: "Conectar",
  CreateInstantInvite: "Crear invitación instantánea",
  CreatePrivateThreads: "Crear hilos privados",
  CreatePublicThreads: "Crear hilos públicos",
  DeafenMembers: "Ensordecer miembros",
  EmbedLinks: "Incrustar enlaces",
  KickMembers: "Expulsar miembros",
  ManageChannels: "Gestionar canales",
  ManageEmojisAndStickers: "Gestionar emojis y pegatinas",
  ManageEvents: "Gestionar eventos",
  ManageGuild: "Gestionar el servidor",
  ManageMessages: "Gestionar mensajes",
  ManageNicknames: "Gestionar apodos",
  ManageRoles: "Gestionar roles",
  ManageThreads: "Gestionar temas",
  ManageWebhooks: "Gestionar webhooks",
  MentionEveryone: "Menciona a todos",
  ModerateMembers: "Moderación de Miembros",
  MoveMembers: "Mover miembros",
  MuteMembers: "Silenciar miembros",
  PrioritySpeaker: "Prioridad al hablar",
  ReadMessageHistory: "Leer historial de mensajes",
  RequestToSpeak: "Petición para hablar",
  SendMessages: "Enviar mensajes",
  SendMessagesInThreads: "Enviar mensajes en hilos",
  SendTTSMessages: "Enviar mensajes TTS",
  Speak: "Hablar",
  Stream: "Vídeo",
  UseApplicationCommands: "Usar comandos de Aplicación",
  UseEmbeddedActivities: "Utilizar actividades integradas",
  UseExternalEmojis: "Usar emoticonos externos",
  UseExternalStickers: "Usar pegatinas externas",
  UseVAD: "Usar actividad de voz",
  ViewAuditLog: "Mirar el registro de auditoria",
  ViewChannel: "Mirar el canal",
  ViewGuildInsights: "Ver información sobre el servidor",
};
